<?php

/**
 * @file
 * Contains kadabrait_content.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function kadabrait_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the kadabrait_content module.
    case 'help.page.kadabrait_content':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('module of test for KadabraIt') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_theme().
 */
function kadabrait_content_theme(): array {
  return [
    'last_content_block' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
  ];
}
